pipeline{
    agent any
    stages{
        stage('Hostname'){
            steps {
                sh '''
                    hostname
                '''  
            }
        }
        stage('Server details'){
            steps{
                sh '''
                    uname -a
                '''
            }
        }
        stage('memory details'){
            steps{
                sh '''
                    free -h
                '''    
            }
        }
        stage('disk details'){
            steps{
                sh '''
                df -kh 
                '''
            }
        }
    }
}